sergiitk/pagerbeauty

src/app/PagerBeautyWebApp.mjs, src/controllers/.eslintrc.js, src/controllers/SchedulesController.mjs
Renders json on
```
/v1/schedules
/v1/schedules/:scheduleId
```
=> Simple web controller and routing

assets/index.html, package.json, src/app/PagerBeautyWebApp.mjs, src/controllers/SchedulesController.mjs, yarn.lock
Display static assets on /assets
=> Static assets

assets/javascripts/application.js, src/controllers/SchedulesController.mjs, src/services/SchedulesService.mjs, src/views/layout.html.j2
=> Refresh schedules

README.md, package.json, yarn.lock
Upgrade dependency tree, add dependencies status badges.
- dotenv
=> Chore: dependencies update

README.md, package.json, pagerbeauty.mjs, src/app/PagerBeautyWebApp.mjs, yarn.lock
Configure Basic HTTP authentication with `PAGERBEAUTY_HTTP_USER` and `PAGERBEAUTY_HTTP_PASSWORD`.
=> Basic HTTP authentication

.github/pull_request_template.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md
=> Rules of contribution

CONTRIBUTING.md, README.md
Add instructions to run the app locally.
=> Add run locally instructions

README.md
- Add to DataDog wallboard instructions
=> DataDog instructions

README.md, package.json
=> Bump version v0.0.7

CONTRIBUTING.md, README.md, package.json
- Update references to GitHub repo: sergii-tkachenko -> sergiitk
=> docs: update references to GitHub repo: sergii-tkachenko -> sergiitk

assets/stylesheets/application.css, src/controllers/SchedulesController.mjs, src/views/schedules/show.html.j2
=> Display "No one on call" to ensure 404 doesn't break widget autorefresh

.circleci/config.yml, package.json
=> Sync Production

.circleci/config.yml, Dockerfile
=> Node upgrade 10.11.0

package.json
=> Sync with production

CHANGELOG.md, package.json
Update changelog automatically.
=> Bugfix changelog

src/controllers/SchedulesController.mjs
- Fixes a bug with refresh rate not being applied. Because of that schedules refresh requests were issued immediately one another
=> [BUGFIX core-schedules] Fix uncontrollable refresh

CHANGELOG.md, package.json
Reintegrate automatic updates
- [43](https://github.com/sergiitk/pagerbeauty/pull/43) **readme** Add sponsors section to README.md
- [44](https://github.com/sergiitk/pagerbeauty/pull/44) **CVE-2018-12120** Upgrade node in Docker to 10.14.2 and refresh npm dependencies
=> 0.0.12 Sync with production

README.md
=> Fix sponsors on README.md

.dockerignore, README.md
- Link Docker repo on README.md
- Update Roadmap
=> [DOC readme] Add dockerhub link, update roadmap

CHANGELOG.md, package.json
- [48](https://github.com/sergiitk/pagerbeauty/pull/48) **chore-dependencies** Dependencies upgrade #38
- [47](https://github.com/sergiitk/pagerbeauty/pull/47) **readme** Add dockerhub link, update roadmap
- [49](https://github.com/sergiitk/pagerbeauty/pull/49) **readme** Wallboard -> dashboard
- [39](https://github.com/sergiitk/pagerbeauty/pull/39) **ui-schedules** Major UI refactoring: modernize assets pipeline and move rendering to React
=> 0.1.0 Sync with production

.dockerignore
- Fixes a bug with production assets not included into the build
=> [BUGFIX docker] Docker should use production assets and ignore dev

README.md, src/assets/javascripts/ui-backend-drivers.jsx, src/assets/javascripts/ui-errors.js, src/assets/javascripts/views/OnCallViews.jsx, src/assets/javascripts/views/StatusIndicatorView.jsx, src/assets/stylesheets/application.scss, src/controllers/SchedulesController.mjs
- OnCallView load status indicator
- OnCallView refactoring 
- UI Improvements and bugixes
=> [FEATURE ui] Add status indicator to on-call

yarn.lock
=> [CLEANUP chore-dependencies] Dependencies upgrade

.circleci/config.yml, CONTRIBUTING.md, Dockerfile, Dockerfile-dev, Dockerfile-test-acceptance, README.md, ava.config.js, package.json
=> [CLEANUP] Prepare for v1.0.0

README.md
Fantastic project! Just one minor nit s/DataDog/Datadog/
=> update caps on Datadog

README.md
- Add PagerBeauty on Grafana Dashboard screenshot
=> [DOC readme] Add PagerBeauty on Grafana Dashboard screenshot

README.md
Add details on PagerBeauty roadmap.
=> [DOC readme] Update roadmap

CONTRIBUTING.md
=> [DOC readme] Typo - Beaty -> Duty

.releaserc.js
Addresses breaking change in semantic release config.
Introduce with a major upgrade in #130
=> Fix semantic release breaking changes

.aws/pagerbeauty.cloudformation
- Provides AWS CloudFormation template
=> Create CloudFormation template

.aws/pagerbeauty.cloudformation, README.md, docs/aws.md
=> Add AWS docs

README.md, src/app/PagerBeautyWorker.js, src/models/ContactMethod.js, src/models/OnCall.js, src/pagerbeauty.js, src/services/OnCallsService.js, test/mocks/users/P6MDP9N/contact_methods/GET.mock, test/mocks/users/PFNNZP8/contact_methods/GET.mock, test/mocks/users/PT6BV4C/contact_methods/GET.mock, test/unit/models/OnCall.test.js
- Contact Methods minor refactoring
=> [CLEANUP io] Limit information exposed though contact methods

.circleci/config.yml, Dockerfile, Dockerfile-dev, Dockerfile-test-acceptance
- Docker: Upgrade node to 12.18.2
=> [CLEANUP chore-dependencies] Docker: Upgrade node to 12.18.2

.circleci/config.yml, Dockerfile, Dockerfile-dev, Dockerfile-test-acceptance, package.json
- Docker: Upgrade node to `14.16.1` (latest LTE)
- package.json: require npm `6.14.12` and yarn `1.22.5`
=> [CLEANUP chore-dependencies] Docker: Upgrade node to 14.16.1

.circleci/config.yml, docker-compose.circleci.yaml
CircleCI heavily limited free VM usage.
=> CircleCI: replace VMs with docker nodes
